name = "Project 3"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["«Project 3»"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "«Project 3»"
